### ISSUE TITLE
Cannot read property 'slice' of null (CRA2)

### ISSUE THREAD

**Issue by lnhrdt** [rubenspgcavalcante/react-instascan#9]
react-instascan throws an error in my projects:

> TypeError: Cannot read property 'slice' of null
> parseJSFunc
> node_modules/instascan/src/zxing.js:4

The projects are created with Create React App 2. CRA2 is currently in alpha but is otherwise very stable and react-instascan is the first dependency I've come across that does not work. Perhaps the issue is within react-instascan.

I've created a repository that reproduces the error:
https://github.com/lnhrdt/react-instascan-error

Any ideas @rubenspgcavalcante?

**Comment by rubenspgcavalcante** [comment]
Hey @lnhrdt , 
I'll check out your repo and see what's happening :)

**Comment by rubenspgcavalcante** [comment]
Checking the stacktrace, the error is happening in one of the dependencies of Instascan (zxing).
To make sure, I did the direct use of Instascan in you repo code and the very same error happened:
```js
import {Camera} from "instascan";
Camera.getCameras().then(cameras => console.log(cameras));
```
Analysing the library code, perhaps it's happening on the internal module resolution of it.
Anyway, you can open a issue on instascan repo reporting this problem :)

**Comment by lnhrdt** [comment]
@rubenspgcavalcante thanks for taking the time to pull down the repo and look into the issue with me. I made an issue in instascan's repo as you suggested.

https://github.com/schmich/instascan/issues/154
